name: GitHub-Profile-3D-Contrib-2
description: Generate profile 3D Contributions With some bug fixes
author: Thecode764

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'box'
  color: 'green'
